### ISSUE TITLE
Urgent!! RuntimeError: faster_rcnn_fbnetv3a_C4.yaml not available in Model Zoo! in d2go

### ISSUE THREAD

**Issue by entbappy** [TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2#11]
Hello there!! I am trying to run your D2GO_Introduction.ipynb file but I am facing some issue with that I am getting that error during getting the model from model zoo ,, "RuntimeError: faster_rcnn_fbnetv3a_C4.yaml not available in Model Zoo"
Here is the snapshot, please consider your feedback.

![image](https://user-images.githubusercontent.com/68845761/152566966-c0cb8bd7-d571-4ede-abd4-3ff2563524b2.png)

**Comment by Rishav-hub** [comment]
Facing the same issue please help @TannerGilbert.

**Comment by TannerGilbert** [comment]
@entbappy, @Rishav-hub just tried it out and I'm getting the same error. Will try to fix this asap.

**Comment by entbappy** [comment]
Sure,, Thanks for your feedback :) @TannerGilbert

**Comment by Morpheushealer73** [comment]
Facing this issue right now using Google Colab. any fix is a great help

**Comment by macdipu** [comment]
facing same!
