### ISSUE TITLE
IOS Support

### ISSUE THREAD

**Issue by sefibk** [TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2#5]
Thank you for this repo.
Does it support IOS instance segmentation or is it only Android?

**Comment by TannerGilbert** [comment]
As of now, there is only [one example for Android](https://github.com/pytorch/android-demo-app/tree/master/D2Go), and there isn't one for [IOS](https://github.com/pytorch/ios-demo-app), but theoretically, it should be possible to use D2Go with IOS too.
