### ISSUE TITLE
How to run Detectron2 in opencv dnn? 

### ISSUE THREAD

**Issue by Jeffin21** [TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2#6]
do you know how to run this .pth file to in opencv dnn ?

**Comment by TannerGilbert** [comment]
I'm not sure, but you might be able to convert the Detectron2 model to Caffe2 and then use it with OpenCV. For more information on how to convert a Detectron2 model to Caffe2, check out my ["Detectron2: Train and export model" notebook](https://github.com/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2/blob/master/Detectron2_train_and_export_model.ipynb).
